version: '3'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_DATABASE: "juMarket_db"
    ports:
      - "3306:3306"

    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    ports:
      - 8888:8080
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge