spring:



  datasource:
    url: jdbc:mysql://localhost:3306/juMarket_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123


  flyway:
    baseline-on-migrate: true

  jpa:
    show-sql: true # mostra no console os comandos sql
    hibernate:
      ddl-auto: none # Para desativar completamente a criação automática de tabelas

      # Vou utilizar o flayway para a criação de tabela



springdoc:
  swagger-ui:
    path: /swagger-ui.html



